-- Virtual texture IDs (range: 100-255).

#define T_WATER            102
#define T_FOUNTAIN         103
#define T_SWAMP            106
#define T_ALTAR            107
#define T_STONE_FLOOR      112
#define T_STONE_WALL       113
#define T_STONE_DOOR       114
#define T_WOOD_PLANKS      115
#define T_WOODEN_DOOR      116
#define T_STONE_GATE       117
#define T_GRASS            118
#define T_TREE             119
#define T_HUT              120
#define T_CAVE_ENTRANCE    121
#define T_TREE_FULL        122
#define T_DIRT             123
#define T_BURIED           124
#define T_BURIED_K         125
#define T_MOUNTAIN         126
#define T_SAND             127
#define T_PALM_TREE        128
#define T_TALL_GRASS       129
#define T_WOODS            130
#define T_FOREST           131
#define T_STONE_ARCH       132
#define T_BROWN_BOULDER    133
#define T_DRY_TREES        134
#define T_EMERALD_GATE     135
#define T_WELL             136
#define T_CHEST            137
#define T_CHEST_K          138
#define T_COARSE_STONE     139
#define T_CAVE_FLOOR       140
#define T_CAVE_WALL        141
#define T_STAIRS_UP        142
#define T_STAIRS_DOWN      143
#define T_IRON_BARS        144
#define T_IRON_BARS_K      145
#define T_LEVER            146
#define T_LEVER_K          147
#define T_ALTAR_K          148
#define T_PILLAR           149
#define T_SIGN             150
#define T_WINDOW           151
#define T_COARSE_DOOR      152
#define T_COARSE_DOOR_K    153
#define T_COARSE_DOOR_L    154
#define T_BOOKSHELF        155
#define T_BOOKSTAND        156 
#define T_BOOKSTAND_K      157
#define T_PYRE             161
#define T_AUT_GRASS        162
#define T_AUT_WOODS        163
#define T_WOOD_GATE        164
#define T_AUT_FOREST       165
#define T_BAMBOO           166
#define T_FANCY_GATE       167
#define T_PALACE_WALL      168
#define T_BOAT             169
#define T_MON_WALL         170
#define T_MON_BANNER       171
#define T_MON_TORCH        172
#define T_MON_WINDOW       173
#define T_MON_DOOR         174
#define T_MON_FLOOR        175
#define T_OBELISK          176
#define T_SAND_WALL        177
#define T_SAND_DOOR        178
#define T_SAND_GATE        179
#define T_TOMB_WALL        180
#define T_TOMB_PANEL       181
#define T_TOMB_FLOOR       182
#define T_TOMB_STAIRS_UP   183
#define T_TOMB_STAIRS_DOWN 184
#define T_FLOWERS          185
#define T_EMERALD_GATE_K   186
#define T_TOMB_WINDOW      187
#define T_SARCOPHAGUS      188
#define T_PORTAL           189
#define T_SNOW_GRASS       190
#define T_SNOW_WOODS       191
#define T_SNOW_ROAD        192
#define T_SNOW_STONE       193
#define T_SNOW_HUT         194
#define T_SNOW_LAKE        195
#define T_SNOW_FOREST      196
#define T_LAVENDER         197
#define T_GRAVE            198
#define T_SWAMP_GRASS      199
#define T_MOSSY_STONE      200
#define T_GRAVE_K          201
#define T_ICE_WALL         202
#define T_ICE_DOOR         203
#define T_ICE_GATE         204
#define T_STATUE           205
#define T_STATUE_K         206
#define T_THRONE           207
#define T_LAVA             208
#define T_FIRE_GROUND      209
#define T_FIRE_COLUMN      210
#define T_FIRE_WOODS       211
#define T_FIRE_WALL        212
-- WARNING: TID is a byte, so max is 255

-- Texture flags
-- If this is set, then it's 2-frame animation
#define TXF_ANIM2 2

-- TLUT header byte (for error checking).
#define TLUT_HDR 92

